### ISSUE TITLE
Low sampling rate in example csv

### ISSUE THREAD

**Issue by IsmailElnaggar** [edgeimpulse/example-data-collection-colmi-r02#2]
Hey,

Looking at the timestamps in your example csv in the readme file, do you know if there's any possibility to increase it to 100 samples per second or something like that? For this second: 13:45:23 it looks like there is 11-12 samples for that second. It could be very hard to extract HR from that sampling rate from the raw ppg data.

Thanks again for sharing this!

**Comment by luisomoreau** [comment]
Hi @IsmailElnaggar,

I am not sure how to modify the firmware to send data even faster. I might dig into that later.
I am working on some post-processing to resample the data at 50Hz now but it will just be a resampling with a linear interpolation.

Best,

Louis

**Comment by IsmailElnaggar** [comment]
@luisomoreau . First I'd like to thank you for your reply and again for providing this repo.

I sadly don't have the necessary knowledge regarding embedded systems to look into this issue myself. What I can say though from looking at the example csv, I see there there are 3 different payloads being sent during that second I mentioned before. So it seems that of the ppg data we can expect to get around 3-4 samples related to the raw ppg.

I have a suspicion that that won't be enough samples to upsample to something usable to extract peaks to calculate heart rate. If we consider an example of someone with a heart rate of 60 bpm. So one beat on average per second. Depending on when those 3-4 samples are taken during that second using a linear interpolation most likely will fail. This problem will be more pronounced as the heart rate increases now there may be more than 1 beat within a second and your linear interpolation will surely miss this. Just wanted to give my two cents! Thanks again and hopefully you find a good solution. This would be a great repo for researchers or people interested in wearables to create their own methods to extract their own biometrics from this relatively cheap ring set up!
